### ISSUE TITLE
Game install defaults to C drive

### ISSUE THREAD

**Issue by dscottwilson** [DrinkFromTheCup/Playnite-Library-Riot#1]
Hello! I have Valorant installed in "D:\Riot Games\VALORANT" but I have the feeling it's only scanning "C:\Riot Games\VALORANT".

If I change the "Installation Folder" to the correct place and check "Installed", it launches fine.

If I update the Riot game library, it changes it to the installation folder to the C directory and sets installed to false. (Which happens every time I launch Playnite)

Is there any way we can either have it automatically detect an install in a different location OR to be able to set our games' install directory (array of possible directories that it scans?) in the Add-on's settings?

Thanks :)

**Comment by DrinkFromTheCup** [comment]
Good day to you!

Somehow, the plugin started overriding install location (and status, by extent) for me too, so no extra intel needed.
Probably, some behind-the-scene changes in Playnite SDK made my initial approach invalid.
So it's time to invent some alternative!
(for "C: only folder scanning" problem too - my mistake, I forgot that _some_ installers allow picking game install location)

It shouldn't take more than a day to have it solved... hopefully...

**Comment by DrinkFromTheCup** [comment]
@dscottwilson , done'n'done!

Can't test it with Valorant explicitly because an attempt to install it would gonna destroy my HDD (probably literally) though. But I did my homework well - and pretty sure that everything will gonna be OK :)

Playnite should propose plugin update on nearest launch.

Closing (but keeping watching)...
