### ISSUE TITLE
Install button installs "Legends of Runeterra" for every riot game

### ISSUE THREAD

**Issue by MoulikRT** [DrinkFromTheCup/Playnite-Library-Riot#2]
Clicking on the install button for any game riot game directly opens up the download for "Legends of Runeterra Installer" only. 
Adding Legends of Runeterra to exclusion list and trying to install the other games still opens up the LoR installer.

**Comment by DrinkFromTheCup** [comment]
Good day to you!

No launcher is installed yet, I assume?

Runeterra is the only Riot's project to date which does not use region-bound installers (nor does it use potentially undesired redistributables as Valorant does).
Since Riot are not providing singular Launcher installer, I had to resort to using Runeterra as the base.
And, as far as I know, Playnite does not offer an option to use game-specific links to launchers yet...

If you did installed Riot launcher earlier - few words about how you did it will help with diagnosing the problem.

Thank you in advance!

**Comment by MoulikRT** [comment]
As it turns out, I'm an idiot. I had installed this plugin a few months ago and didn't really play any riot games since then and so had deleted those games.
What I didn't realize is that I had also at one point deleted the Riot Games Launcher when I probably cleaned out my storage. I installed the riot games client and everything works perfectly now.
Sorry for the trouble; this was not my finest moment. 🤦‍♂️
